### ISSUE TITLE
I can't compile the second example on my computer

### ISSUE THREAD

**Issue by seamanj** [libigl/libigl#138]
![image](https://cloud.githubusercontent.com/assets/10722187/10642268/b9357c58-7814-11e5-9d29-216607055251.png)
As the image shown above, when I try to compile the second example of the tutorial, it prompts some error, help!

**Comment by danielepanozzo** [comment]
This could be an issue related with using gcc on windows. Could you try to use visual studio 2015 to compile and see if you get the same error?

**Comment by seamanj** [comment]
Hi,there!

I've changed for VS2015, now I have new problems. Here is my errors:

![image](https://cloud.githubusercontent.com/assets/10722187/10667432/48473728-78cf-11e5-81ad-d9b61e11376e.png)

Severity	Code	Description	Project	File	Line
Error	LNK2019	unresolved external symbol _nvgBeginFrame referenced in function "public: void __thiscall igl::viewer::TextRenderer::BeginDraw(class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,1,0,4,1> const &,float)" (?BeginDraw@TextRenderer@viewer@igl@@QAEXABV?$Matrix@M$03$03$0A@$03$03@Eigen@@0ABV?$Matrix@M$03$00$0A@$03$00@5@M@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK1120	11 unresolved externals	Ex102	G:\TestIgl\Ex102\Debug\Ex102.exe	1
Error (active)		no instance of overloaded function "igl::sort" matches the specified type	Ex102	d:\work_files\libigl\include\igl\sort.cpp	238
Error	LNK2019	unresolved external symbol _nvgCreateFontMem referenced in function "public: virtual int __thiscall igl::viewer::TextRenderer::Init(void)" (?Init@TextRenderer@viewer@igl@@UAEHXZ)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgCreateGL3 referenced in function "public: virtual int __thiscall igl::viewer::TextRenderer::Init(void)" (?Init@TextRenderer@viewer@igl@@UAEHXZ)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgDeleteGL3 referenced in function "public: virtual int __thiscall igl::viewer::TextRenderer::Shut(void)" (?Shut@TextRenderer@viewer@igl@@UAEHXZ)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgEndFrame referenced in function "public: void __thiscall igl::viewer::TextRenderer::EndDraw(void)" (?EndDraw@TextRenderer@viewer@igl@@QAEXXZ)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgFillColor referenced in function "public: void __thiscall igl::viewer::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@viewer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgFontFace referenced in function "public: void __thiscall igl::viewer::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@viewer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgFontSize referenced in function "public: void __thiscall igl::viewer::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@viewer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgRGBA referenced in function "public: void __thiscall igl::viewer::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@viewer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgText referenced in function "public: void __thiscall igl::viewer::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@viewer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1
Error	LNK2019	unresolved external symbol _nvgTextAlign referenced in function "public: void __thiscall igl::viewer::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@viewer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Ex102	G:\TestIgl\Ex102\Ex102\main.obj	1

need some advices,thx!

**Comment by seamanj** [comment]
seems like the nanovg.c isn't compiled in nanogui.lib

**Comment by seamanj** [comment]
![image](https://cloud.githubusercontent.com/assets/10722187/10671790/7812842a-78e4-11e5-94a9-327a24222d1a.png)

**Comment by seamanj** [comment]
![image](https://cloud.githubusercontent.com/assets/10722187/10671800/8cabf114-78e4-11e5-8bda-a51dbb71cbac.png)

**Comment by danielepanozzo** [comment]
I think you are opening the wrong project. You should launch cmake in the folder libigl/tutorial and compile all the tutorials at once in a single visual studio solution. 

The single examples cannot be compiled independently.

**Comment by seamanj** [comment]
Hi, daniel, 

thanks for replying, I just did as you said, but there are some new errors produced, could you help me?

![image](https://cloud.githubusercontent.com/assets/10722187/10673128/128b949a-78ec-11e5-80c7-ffa98f43dc06.png)

**Comment by seamanj** [comment]
Finally, I am able to make the Ex102 out.
![image](https://cloud.githubusercontent.com/assets/10722187/10673477/ffa4d1e6-78ed-11e5-948b-5979dee10ad0.png)

But here is a new question, how can I compile Ex102 independently. You know, if I want to write a procedure(suppose Ex102) with igl library, of course, the procedure is independent with the tutorial. How could I  compile the procedure(such as Ex102) independently.

Regards
Seamanj

**Comment by seamanj** [comment]
Thanks, I 've just figured it out, if there is someone need to know, please visit my chinese blog.
http://blog.csdn.net/seamanj/article/details/49369517
XDDDDD
