### ISSUE TITLE
Cgal::intersect_other does not work with boost 1.54

### ISSUE THREAD

**Issue by Wouter92** [libigl/libigl#239]
Just wanted to notice that `igl::copyleft::cgal::intersect_other` does not work with boost version 1.54 (standard on Ubuntu 14.04). 

When I tried this I got a lot [https://gist.github.com/Wouter92/0194cb7c39f0f10bc5c9560053302746](compilation errors). It works when using Boost 1.60, for example. But maybe this is more of a CGAL issue?

**Comment by alecjacobson** [comment]
This does seem like more of a CGAL issue. If you find an answer, you could link it here if others have the same issue. Good luck.
