### ISSUE TITLE
GCC 7.4 compilation error in bfs_orient

### ISSUE THREAD

**Issue by prashantraina** [libigl/libigl#1420]
The following line fails to compile on GCC 7.4:

https://github.com/libigl/libigl/blob/87b54fc4dcc5aea182dd842a55ac75536fb69e1a/include/igl/bfs_orient.cpp#L33

The error message is:
```
error: comparison between distinct pointer types ‘Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1> >*’ and ‘const Eigen::PlainObjectBase<Eigen::Matrix<int, -1, -1, 1> >*’ lacks a cast
   if(&FF != &F)
      ~~~~^~~~~
```

### Workaround

It works after I changed it to:
``
if(reinterpret_cast<decltype(&F)>(&FF) != &F)
``

**Comment by alecjacobson** [comment]
It seems that this was fixed with

```cpp
if(((void*)&FF) != ((void*)&F))
```

not sure if that's a general solution. If it is, I guess there are a bunch of functions that could use it as a way to avoid a copy and operate "in place". If someone chimes in that they think it's kosher great, otherwise just leaving as is and closing this old issue.
