### ISSUE TITLE
ShapeUp.cpp Error with VS2017 (Eigen 3.4.4) When Building IGL As A Static Library

### ISSUE THREAD

**Issue by adam-hartshorne** [libigl/libigl#730]
When attempting to build the latest version from github as a static library, during the compilation of igl_core with VS2017 using Eigen 3.4.4, I get the following error in shapeup.cpp

libigl\include\igl\shapeup.cpp(209): error C2248: 'Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>>::PlainObjectBase': cannot access protected member declared in class 'Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>>'

**Comment by jdumas** [comment]
Does it compile with Eigen 3.2 that is included in libigl's repository?

**Comment by oracle3001** [comment]
Yes it does. 

It must be a fairly recent change as I previously built libigl with 3.3.4 about two to three months ago, and this is the only error I get with 3.3.4.

**Comment by jdumas** [comment]
Yes this is a new function that has been merged recently. We do not build with Eigen 3.3 yet in Travis, so when those errors pop up we do not see them.

Can you replace the line 209 that doesn't compile with the following, and see if that fixes it:
```
DerivedP lsrhs=-sudata.At*sudata.W*rhs;
```
