### ISSUE TITLE
mesh_boolean.h: Eigen + CGAL compilation error

### ISSUE THREAD

**Issue by ataber** [libigl/libigl#596]
Hi, I'm having an issue compiling `mesh_boolean.h`. 

I'm compiling Eigen 3.3.4 (I have also tried 3.3.3, with the same result), CGAL 4.7-4 (installed via `apt-get`), with g++ 5.4.0.

I see three compiler errors:
```
../../third_party/eigen/Eigen/src/Core/util/XprHelper.h:64:8: error: no type named 'Literal' in 'struct Eigen::NumTraits<CGAL::Lazy_exact_nt<CGAL::Gmpq> >'
 struct promote_scalar_arg<S,T,false> : promote_scalar_arg_unsupported<S,T,typename NumTraits<S>::Literal> {};
```

```
../../third_party/libigl/include/igl/copyleft/cgal/extract_cells.cpp:190:62: error: no match for 'operator/' (operand types are 'const Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq> >, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<CGAL::Lazy_exact_nt<CGAL::Gmpq>, CGAL::Lazy_exact_nt<CGAL::Gmpq> >, const Eigen::Block<const Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, 1, -1, false>, const Eigen::Block<const Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, 1, -1, false> >, const Eigen::Block<const Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, 1, -1, false> >' and 'double')
     return ((V.row(F(fid,0))+V.row(F(fid,1))+V.row(F(fid,2)))/3.0).eval();
                                                              ^
```
and 
```
../../third_party/libigl/include/igl/copyleft/cgal/extract_cells.cpp:241:28: error: use of 'igl::copyleft::cgal::extract_cells(const Eigen::PlainObjectBase<Derived>&, const Eigen::PlainObjectBase<DerivedD>&, const Eigen::PlainObjectBase<DerivedVC>&, const Eigen::PlainObjectBase<DerivedFC>&, const Eigen::PlainObjectBase<DerivedVC>&, const std::vector<std::vector<uE2EType> >&, const Eigen::PlainObjectBase<DerivedJ>&, Eigen::PlainObjectBase<DerivedC>&)::<lambda(size_t, size_t)> [with DerivedV = Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>; DerivedF = Eigen::Matrix<int, -1, -1>; DerivedP = Eigen::Matrix<int, -1, 1>; DerivedE = Eigen::Matrix<int, -1, -1>; DeriveduE = Eigen::Matrix<int, -1, -1>; uE2EType = long unsigned int; DerivedEMAP = Eigen::Matrix<int, -1, 1>; DerivedC = Eigen::Matrix<int, -1, -1>; size_t = long unsigned int]' before deduction of 'auto'
         if (bbox_intersects(i,j)) candidate_comps.push_back(j);
                            ^
../../third_party/libigl/include/igl/copyleft/cgal/extract_cells.cpp:256:24: error: no match for 'operator=' (operand types are 'Eigen::DenseBase<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1> >::RowXpr {aka Eigen::Block<Eigen::Matrix<CGAL::Lazy_exact_nt<CGAL::Gmpq>, -1, -1, 0, -1, -1>, 1, -1, false>}' and 'void')
         queries.row(j) = get_triangle_center(outer_facets[index]);
                        ^
```

My code is so trivial I'm fairly certain it's not coming from that.
```
#include "igl/copyleft/cgal/mesh_boolean.h"
using namespace Eigen;

int main(int argc, char** argv) {
  MatrixXd box_vertex(8, 3);
  # ... fill in box_vertex ...
  const MatrixXi box_face = (MatrixXi(12,3) <<
    1, 7, 5,
    1, 3, 7,
    1, 4, 3,
    1, 2, 4,
    3, 8, 7,
    3, 4, 8,
    5, 7, 8,
    5, 8, 6,
    1, 5, 6,
    1, 6, 2,
    2, 6, 8,
    2, 8, 4).finished().array() - 1;
   MatrixXd mesh_vertex(n_vert, 3);
   MatrixXi mesh_face(n_face, 3);
   # ... fill in mesh_vertex, mesh_face ...
   MatrixXd intersect_vertex;
   MatrixXi intersect_face;
   igl::copyleft::cgal::mesh_boolean(
     box_vertex,
     box_face,
     mesh_vertex,
     mesh_face,
     igl::MESH_BOOLEAN_TYPE_INTERSECT,
     intersect_vertex,
     intersect_face
  ); 
}
```
Am I missing something? 

Thanks for the awesome library!

**Comment by ataber** [comment]
This might be related to [this issue](https://github.com/libigl/libigl/issues/432)

**Comment by ataber** [comment]
This issue is fixed when I compile with Eigen 3.2.9.

**Comment by alecjacobson** [comment]
Eigen 3.3.* is unstable and we currently only support 3.2.9 and up.

**Comment by ataber** [comment]
Understood, thanks! What's the timeline for supporting 3.3?

**Comment by alecjacobson** [comment]
Unsure. Last I checked was couple months ago and there were still some
scary bugs in Eigen.

**Comment by ataber** [comment]
Okay makes sense. Eigen's maintainers claim 3.3.* is stable, but that doesn't mean much if there's deal-breaking bugs :-)
