### ISSUE TITLE
Could not open pthread.h

### ISSUE THREAD

**Issue by ygrimault** [libigl/libigl#1034]
When trying to reproduce example 106 with ImGUI, I'm running into a linking error that says

```Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/.../CMakeFiles/CMakeTmp

Run Build Command:"C:/PROGRA~2/MICROS~4/2017/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe" "cmTC_60c2b"
[1/2] Building C object CMakeFiles\cmTC_60c2b.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_60c2b.dir/CheckIncludeFile.c.obj 

C:\PROGRA~2\MICROS~4\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x64\cl.exe   /nologo   /DWIN32 /D_WINDOWS /W3  /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_60c2b.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_60c2b.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.
```

I'm trying to compile in QtCreator, with CMake 3.4 (also tried CMake 3.5), MSCV 2017 and Ninja. I'm running on Windows 10.

Here is my CMakeLists:

```cmake_minimum_required(VERSION 2.8)
project(SculpturePaintings)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

# libigl
option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)
option(LIBIGL_WITH_VIEWER            "Use OpenGL viewer"  ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI "Use ImGui"          ON)

find_package(LIBIGL REQUIRED QUIET)

# Add your project files
file(GLOB SRCFILES src/*.cpp)
add_executable(${PROJECT_NAME} ${SRCFILES})
target_link_libraries(${PROJECT_NAME} igl::core igl::opengl igl::opengl_glfw igl::opengl_glfw_imgui)
```

(I'm sorry if I forgot any information, I wrote it quickly before a meeting)

#### Check all that apply (change to `[x]`)
- [x] Windows
- [ ] Mac OS X
- [ ] Linux

See <https://libigl.github.io/CONTRIBUTING/#bugreport> for more tips.

**Comment by ygrimault** [comment]
I'm compiling in QtCreator as my IDE, but I'm using MSVC as a compiler (QtCreator doesn't have one).
I took the CMake file from your tutorials, and it works fine if I don't use ImGUI.

**Comment by ygrimault** [comment]
Hello,
Thanks to your advise, I tried to generate the project using CMake-GUI, but I encountered another problem. By solving it, it solved my first problem too, I think I got lucky :D

So for anyone who has the same problem, you might want to check this solution: https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe
I'm not sure whether it was adding the said location to $PATH$ or making a copy of the files that solved the problem, but it seems it did.
