### ISSUE TITLE
fatal error: GL/glcorearb.h: No such file or directory

### ISSUE THREAD

**Issue by KeeganRen** [libigl/libigl#241]
Ubuntu 14.04 LTS, GTX 970M:

Scanning dependencies of target iglviewer
[ 54%] Building CXX object libigl/CMakeFiles/iglviewer.dir/home/ren/Compile/libigl/include/igl/viewer/ViewerCore.cpp.o
[ 54%] Building CXX object libigl/CMakeFiles/iglviewer.dir/home/ren/Compile/libigl/include/igl/viewer/OpenGL_state.cpp.o
[ 54%] Building CXX object libigl/CMakeFiles/iglviewer.dir/home/ren/Compile/libigl/include/igl/viewer/ViewerData.cpp.o
[ 54%] Building CXX object libigl/CMakeFiles/iglviewer.dir/home/ren/Compile/libigl/include/igl/viewer/Viewer.cpp.o
In file included from /home/ren/Compile/libigl/include/igl/viewer/Viewer.cpp:38:0:
/home/ren/Compile/libigl/shared/cmake/../../external/nanogui/ext/glfw/include/GLFW/glfw3.h:131:28: fatal error: GL/glcorearb.h: No such file or directory
   #include <GL/glcorearb.h>
                            ^
compilation terminated.
make[2]: **\* [libigl/CMakeFiles/iglviewer.dir/home/ren/Compile/libigl/include/igl/viewer/Viewer.cpp.o] Error 1
make[1]: **\* [libigl/CMakeFiles/iglviewer.dir/all] Error 2
make: **\* [all] Error 2

**Comment by danielepanozzo** [comment]
Looks like you are missing some basic opengl packages. We have a continuous build on linux 12.04, you can take a look at the travis file to find which ones you are missing:

https://github.com/libigl/libigl/blob/master/.travis.yml

**Comment by KeeganRen** [comment]
Thanks, I have solve this problem by : https://travis-ci.org/libigl/libigl/jobs/120917497#L106

**Comment by eshafeeqe** [comment]
@KeeganRen can you explain me how you resolved this issue? I also came across the same issue

**Comment by danielepanozzo** [comment]
cd libigl
wget -P external/nanogui/ext/glfw/include/GL http://www.opengl.org/registry/api/GL/glcorearb.h

should fix the issue.

**Comment by eshafeeqe** [comment]
ooh thanks a ton :dancer: it fixed the issue
