### ISSUE TITLE
Upgrade to Eigen 3.3

### ISSUE THREAD

**Issue by AnthonyVogelweid** [libigl/libigl#989]
Hi,

I need to implement the igl library inside a project using Eigen 3.3. Consequently, I've some errors due to conflict between Eigen versions.

I want to use Eigen 3.3.3 with igl, is it possible ? If not, why igl can't use Eigen 3.3 ?

I've read an issue about that : https://github.com/libigl/eigen/issues/1

Do you have some news about this issue ? Did someone try to use Eigen 3.3 with igl ?

**Comment by jdumas** [comment]
What errors do you get exactly? I've used libigl in a project with Eigen 3.3 without any trouble. If you define a target `Eigen3::Eigen` in your CMake before including libigl, it will use that one instead of downloading/using its own version of Eigen. Usually compilations issues are also easily fixed and are becoming more few and far between.

We're planning to move to Eigen 3.3 once we consolidate our unit tests framework and coverage, so it's gonna happen soon once this is done.

**Comment by AnthonyVogelweid** [comment]
It wasn't compilation errors but memory error on runtime because, I suppose, some part of my project use Eigen 3.3 and igl part use Eigen 3.2. If there are no trouble to use igl with Eigen 3.3, I will only use Eigen 3.3

**Comment by fwilliams** [comment]
If you're hitting bugs with libIGL and Eigen 3.3, we'd love to have more details on them since we plan on bumping the version of Eigen relatively soon. Could you isolate the part of your code where the error occurs and post a little more details? 

In the `dev-python` branch, we're using Eigen 3.3 with the new Python bindings without any problems. Admittedly we are only calling a subset of the code and we're compiling header only. As Jeremie pointed out, if you set the `Eigen3::Eigen` target, then libIGL should just use that version of Eigen. It's very unlikely that you somehow compiled with some headers from Eigen 3.2 and some from Eigen 3.3.

**Comment by jdumas** [comment]
Well, compiling with both Eigen 3.2 and 3.3 in the same codebase is just asking for trouble. Eigen 3.3 should work fine with libigl, but of course there is no guarantee: it hasn't been run through the unit tests, and most of us are using Eigen 3.2 with libigl. Nothing prevents you to use Eigen 3.3 though, and if you have any feedback or spot a bug feel free to let us know.

**Comment by AnthonyVogelweid** [comment]
Yes sure, I would like to upgrade to Eigen 3.3 and check if this error occur again.

Now, I can't compile with eigen 3.3.3 I get some errors : 

It come from : libigl/include/igl/copyleft/cgal/mesh_boolean.h:15: `eigen-3.3.3/Eigen/src/Core/util/XprHelper.h:64:98: error: no type named 'Literal' in 'Eigen::NumTraits >'`: `struct promote_scalar_arg : promote_scalar_arg_unsupported::Literal> {};`

And 

`libigl/include/igl/copyleft/cgal/extract_cells.cpp:190:62: error: invalid operands to binary expression ('const CwiseBinaryOp, Lazy_exact_nt >, const Block, -1, -1, 0, -1, -1>, 1, -1, false>, const Block, -1, -1, 0, -1, -1>, 1, -1, false> > >::Scalar, typename internal::traits, -1, -1, 0, -1, -1>, 1, -1, false> >::Scalar>, const Eigen::CwiseBinaryOp, CGAL::Lazy_exact_nt >, const Eigen::Block, -1, -1, 0, -1, -1>, 1, -1, false>, const Eigen::Block, -1, -1, 0, -1, -1>, 1, -1, false> >, const Eigen::Block, -1, -1, 0, -1, -1>, 1, -1, false> >' (aka 'const CwiseBinaryOp, CGAL::Lazy_exact_nt >, const Eigen::CwiseBinaryOp, CGAL::Lazy_exact_nt >, const Eigen::Block, -1, -1, 0, -1, -1>, 1, -1, false>, const Eigen::Block, -1, -1, 0, -1, -1>, 1, -1, false> >, const Eigen::Block, -1, -1, 0, -1, -1>, 1, -1, false> >') and 'double')`

` return ((V.row(F(fid,0))+V.row(F(fid,1))+V.row(F(fid,2)))/3.0).eval();
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
`

**Comment by AnthonyVogelweid** [comment]
The operating system is Ubuntu 16.04.1 and it compile with CGAL.

**Comment by jdumas** [comment]
Well I was asking if you could try to compile without CGAL :D

**Comment by AnthonyVogelweid** [comment]
Oh sorry, no I get numerous undefined reference like `undefined reference to `__gmpq_init'` `undefined reference to `mpfr_clear'` or `undefined reference to `CGAL::assertion_fail(char const*, char const*, int, char const*)'` and so on

**Comment by jdumas** [comment]
I take it that your project is using libigl's CGAL functions?

**Comment by AnthonyVogelweid** [comment]
Yes, I use this function `igl::copyleft::cgal::mesh_boolean`

**Comment by jdumas** [comment]
Well I'm not sure what's going on, so you'd either need to debug it yourself, or wait till we officially move to Eigen 3.3.

**Comment by VAnthony** [comment]
Hello, 

I've moved to eigen 3.3.3 with success and I don't have memory error anymore.

To fix my compilation error, I've updated CGAL (4.7 to 4.11).

For now, igl work correctly with Eigen 3.3.3

I hope that will help you

**Comment by AnthonyVogelweid** [comment]
Finally, i've moved to eigen 3.3.3 with success and I don't have memory error anymore.

To fix my compilation error, I've updated CGAL (4.7 to 4.11).

For now, igl work correctly with Eigen 3.3.3

I hope that will help you

**Comment by abhishek31704** [comment]
Hello,
Could someone let me know the problem with this part of code. I have gmpd.dll in place but still get this error. 
![mpfr error](https://user-images.githubusercontent.com/13964868/112458439-12b10c80-8d5d-11eb-9b4c-0317e4db7162.JPG)
